export const FETCH_DISCOVER_MOVIES = 'FETCH_DISCOVER_MOVIES';
export const FETCH_POPULAR_MOVIES = 'FETCH_POPULAR_MOVIES';
export const FETCH_NOW_PLAY_MOVIES = 'FETCH_NOW_PLAY_MOVIES';
export const FETCH_TOP_RATED_MOVIES = 'FETCH_TOP_RATED_MOVIES';
export const FETCH_UPCOMING_MOVIES = 'FETCH_UPCOMING_MOVIES';
export const FETCH_MOVIE_GENRE = 'FETCH_MOVIE_GENRE';
export const FETCH_MOVIE_CATEGORY = 'FETCH_MOVIE_CATEGORY';
